package com.upc.imageselector.service;

import com.upc.imageselector.config.AppProperties;
import com.upc.imageselector.model.ImageInfo;
import com.upc.imageselector.model.ImageScore;
import com.upc.imageselector.model.ProcessingResult;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVPrinter;
import org.springframework.stereotype.Service;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

@Service
@Slf4j
@RequiredArgsConstructor
public class ExportService {

    private static final DateTimeFormatter DT = DateTimeFormatter.ISO_LOCAL_DATE_TIME;

    private final AppProperties props;

    // ── generate on-disk files ─────────────────────────────────────────────────

    public void generateOutputFiles(Map<String, ProcessingResult> results) throws IOException {
        writeTxt(results);
        writeCsv(results);
    }

    // ── streaming for HTTP download ───────────────────────────────────────────

    public void streamTxt(Map<String, ProcessingResult> results, OutputStream out) throws IOException {
        PrintWriter w = new PrintWriter(new OutputStreamWriter(out, StandardCharsets.UTF_8));
        writeTxtLines(results, w);
        w.flush();
    }

    public void streamCsv(Map<String, ProcessingResult> results, OutputStream out) throws IOException {
        try (BufferedWriter w = new BufferedWriter(new OutputStreamWriter(out, StandardCharsets.UTF_8));
             CSVPrinter csv = buildCsvPrinter(w)) {
            appendCsvRows(results, csv);
        }
    }

    // ── internal helpers ──────────────────────────────────────────────────────

    private void writeTxt(Map<String, ProcessingResult> results) throws IOException {
        Path file = Path.of(props.getSelectedDir(), "selected_front_images.txt");
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(file, StandardCharsets.UTF_8))) {
            writeTxtLines(results, w);
        }
        log.info("Wrote TXT export to {}", file);
    }

    private void writeTxtLines(Map<String, ProcessingResult> results, PrintWriter w) {
        w.println("# Generated by UPC Image Selector");
        w.println("# Generated at: " + LocalDateTime.now().format(DT));
        w.println("# Total UPCs: " + results.size());
        w.println();
        results.values().stream()
                .filter(ProcessingResult::hasValidSelection)
                .sorted(Comparator.comparing(ProcessingResult::getUpc))
                .forEach(r -> w.println(r.getSelectedFilename()));
    }

    private void writeCsv(Map<String, ProcessingResult> results) throws IOException {
        Path file = Path.of(props.getSelectedDir(), "selected_front_images.csv");
        try (BufferedWriter w = Files.newBufferedWriter(file, StandardCharsets.UTF_8);
             CSVPrinter csv = buildCsvPrinter(w)) {
            appendCsvRows(results, csv);
        }
        log.info("Wrote CSV export to {}", file);
    }

    private CSVPrinter buildCsvPrinter(Appendable out) throws IOException {
        String[] headers = {
                "UPC", "SelectedFilename", "ImageType",
                "TotalScore", "ResolutionScore", "SharpnessScore",
                "BrightnessScore", "ContrastScore", "BackgroundScore", "CenteringScore",
                "Width", "Height", "FileSizeBytes",
                "ManualOverride", "ProcessedAt", "OverriddenAt"
        };
        return CSVFormat.DEFAULT.builder()
                .setHeader(headers)
                .build()
                .print(out);
    }

    private void appendCsvRows(Map<String, ProcessingResult> results, CSVPrinter csv) throws IOException {
        for (ProcessingResult r : results.values().stream()
                .sorted(Comparator.comparing(ProcessingResult::getUpc)).toList()) {

            ImageInfo sel = r.getSelectedImage();
            ImageScore sc = sel != null ? sel.getScore() : null;

            csv.printRecord(
                    r.getUpc(),
                    r.getSelectedFilename(),
                    sel != null ? sel.getImageType() : "",
                    sc != null ? sc.getTotalScore() : "",
                    sc != null ? sc.getResolutionScore() : "",
                    sc != null ? sc.getSharpnessScore() : "",
                    sc != null ? sc.getBrightnessScore() : "",
                    sc != null ? sc.getContrastScore() : "",
                    sc != null ? sc.getBackgroundScore() : "",
                    sc != null ? sc.getCenteringScore() : "",
                    sel != null ? sel.getWidth() : "",
                    sel != null ? sel.getHeight() : "",
                    sel != null ? sel.getFileSizeBytes() : "",
                    r.isManualOverride(),
                    r.getProcessedAt() != null ? r.getProcessedAt().format(DT) : "",
                    r.getOverriddenAt() != null ? r.getOverriddenAt().format(DT) : ""
            );
        }
    }
}
